apiVersion: apps/v1
kind: Deployment
metadata:
  name: hgbuggy-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hgbuggy
  template:
    metadata:
      labels:
        app: hgbuggy
    spec:
      containers:
      - name: hgbuggy
        image: 145988340565.dkr.ecr.us-west-2.amazonaws.com/asg
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: hgbuggy
    k8s-app: hgbuggy
  name: hgbuggy
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  type: LoadBalancer
  selector:
    app: hgbuggy
